# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cgvMovieApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire', '~>5.2'
	pod 'SnapKit', '~>5.0.0'
  # Pods for cgvMovieApp

end
