# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ClockApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'SnapKit'
  # Pods for ClockApp

  target 'ClockAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ClockAppUITests' do
    # Pods for testing
  end

end
